# user_api无法启动
## 问题发现
在部署user_api时，容器无法成功启动
```shell
2024-06-08 10:49:26 goroutine 1 [running]:
2024-06-08 10:49:26 runtime/debug.Stack()
2024-06-08 10:49:26     /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
2024-06-08 10:49:26 github.com/zeromicro/go-zero/core/logx.Must({0x22c6b00?, 0xc0001323c0?})
2024-06-08 10:49:26     /go/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/core/logx/logs.go:225 +0x4e
2024-06-08 10:49:26 github.com/zeromicro/go-zero/zrpc.MustNewClient({{{0xc000321de0, 0x1, 0x1}, {0xc0006d3760, 0xb}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
2024-06-08 10:49:26     /go/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/zrpc/client.go:45 +0x65
2024-06-08 10:49:26 fim_server/fim_user/user_api/internal/svc.NewServiceContext({{{{0xc0007a8160, 0x4}, {{...}, {...}, {...}, {...}, {...}, {...}, 0x0, 0x0, ...}, ...}, ...}, ...})
2024-06-08 10:49:26     /build/fim_user/user_api/internal/svc/servicecontext.go:37 +0x188
2024-06-08 10:49:26 main.main()
2024-06-08 10:49:26     /build/fim_user/user_api/users.go:28 +0x147
2024-06-08 10:49:26 
2024-06-08 10:50:26 2024-06-08 10:50:26  error  bad resolver state      caller=internal/discovbuilder.go:34
2024-06-08 10:50:29 2024/06/08 10:50:29 rpc dial: etcd://10.0.0.22:2379/chatrpc.rpc, error: context deadline exceeded, make sure rpc service "chatrpc.rpc" is already started
```
可能是etcd出现了问题，**但我不清楚为什么其他服务能够正常运行，而user_api无法正常运行**
## 问题查找
### etcd服务排查
我进入etcd所在容器命令行，想看看user_api所需要的chatrpc.rpc信息是否在etcd中
```shell
C:\Users\shiji>docker exec -it deploy-etcd-1 /bin/bash
```
执行命令时发现etcd好像出现了问题
```shell
I have no name!@a3887159a044:/opt/bitnami/etcd$ etcdctl get --prefix ""
{"level":"warn","ts":"2024-06-08T02:45:43.860045Z","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000ee380/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
```
直接使用命令用的是127.0.0.1，而我的etcd使用了创建的内网，更改命令后成功获取数据
```shell
I have no name!@a3887159a044:/opt/bitnami/etcd$ etcdctl --endpoints=http://10.0.0.22:2379 get --prefix ""
auth_api
10.0.0.3:20021
chat_api
10.0.0.4:20023
file_api
10.0.0.6:20025
filerpc.rpc/7587879232462156306
10.0.0.7:30023
grouprpc.rpc/7587879232462156312
10.0.0.9:30024
logs_api
10.0.0.10:20027
settings_api
10.0.0.11:20026
settingsrpc.rpc/7587879232462156309
10.0.0.12:8080
userrpc.rpc/7587879232462156299
10.0.0.14:30021
I have no name!@a3887159a044:/opt/bitnami/etcd$
```
发现确实没有chatrpc.rpc服务的信息
### chat_rpc服务排查
查看chat_rpc容器日志：
```shell
2024-06-08 11:15:54 goroutine 1 [running]:
2024-06-08 11:15:54 fim_server/core.InitGorm({0xc00028e0c0, 0x59})
2024-06-08 11:15:54     /build/core/mysql.go:12 +0x189
2024-06-08 11:15:54 fim_server/fim_chat/chat_rpc/internal/svc.NewServiceContext(...)
2024-06-08 11:15:54     /build/fim_chat/chat_rpc/internal/svc/servicecontext.go:15
2024-06-08 11:15:54 main.main()
2024-06-08 11:15:54     /build/fim_chat/chat_rpc/chatrpc.go:27 +0x10b
2024-06-08 11:16:15 panic: 连接mysql数据库失败, error=dial tcp 172.23.208.1:3306: connect: connection refused
```
很可能是无法连接mysql，所以没有将服务信息注册到etcd中
我去找到了部署chat_rpc的yaml文件，发现其中的mysql没有使用内网ip
更改为正确的内网ip后，重启chat_rpc服务
### 重启chat_rpc服务
重启成功，日志如下：
```shell
2024-06-08 11:26:54 panic: 连接mysql数据库失败, error=dial tcp 10.0.0.20:3306: connect: connection refused
2024-06-08 11:26:54 
2024-06-08 11:26:54 goroutine 1 [running]:
2024-06-08 11:26:54 fim_server/core.InitGorm({0xc00021ea20, 0x54})
2024-06-08 11:26:54     /build/core/mysql.go:12 +0x189
2024-06-08 11:26:54 fim_server/fim_chat/chat_rpc/internal/svc.NewServiceContext(...)
2024-06-08 11:26:54     /build/fim_chat/chat_rpc/internal/svc/servicecontext.go:15
2024-06-08 11:26:54 main.main()
2024-06-08 11:26:54     /build/fim_chat/chat_rpc/chatrpc.go:27 +0x10b
2024-06-08 11:26:54 
2024-06-08 11:26:54 2024/06/08 11:26:54 /build/core/mysql.go:10
2024-06-08 11:26:54 [error] failed to initialize database, got error dial tcp 10.0.0.20:3306: connect: connection refused
2024-06-08 11:26:57 连接mysql数据库成功
2024-06-08 11:26:57 Starting rpc server at 0.0.0.0:30022...
```
etcd信息中，chat_rpc正常：
```shell
C:\Users\shiji>docker exec -it deploy-etcd-1 /bin/bash
I have no name!@a3887159a044:/opt/bitnami/etcd$ etcdctl --endpoints=http://10.0.0.22:2379 get --prefix ""
auth_api
10.0.0.3:20021
chat_api
10.0.0.4:20023
chatrpc.rpc/7587879233419026180
10.0.0.5:30022
file_api
10.0.0.6:20025
filerpc.rpc/7587879233419026188
10.0.0.7:30023
grouprpc.rpc/7587879233419026192
10.0.0.9:30024
logs_api
10.0.0.10:20027
settings_api
10.0.0.11:20026
settingsrpc.rpc/7587879233419026199
10.0.0.12:8080
user_api
10.0.0.13:20022
userrpc.rpc/7587879233419026193
10.0.0.14:30021
```
user_api成功启动
```shell
2024-06-08 11:25:16 连接mysql数据库成功
2024-06-08 11:25:16 2024-06-08 11:25:16  info   地址上送成功 user_api  10.0.0.13:20022  caller=etcd/delivery_address.go:29
2024-06-08 11:25:16 Starting server at 0.0.0.0:20022...
2024-06-08 11:25:33 2024-06-08 11:25:33  info   Got signal 15, shutting down... caller=proc/shutdown.go:58
```
# group_api无法启动
## 问题发现
deploy-group_api-1日志文件
```shell
2024-06-08 11:53:59 连接mysql数据库成功
2024-06-08 11:52:59 
2024-06-08 11:53:59 2024/06/08 11:53:59 empty etcd hosts
2024-06-08 11:53:59 
2024-06-08 11:53:59 goroutine 1 [running]:
2024-06-08 11:53:59 runtime/debug.Stack()
2024-06-08 11:53:59     /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
2024-06-08 11:53:59 github.com/zeromicro/go-zero/core/logx.Must({0x2311140?, 0x33729a0?})
2024-06-08 11:53:59     /go/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/core/logx/logs.go:225 +0x4e
2024-06-08 11:53:59 github.com/zeromicro/go-zero/zrpc.MustNewClient({{{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
2024-06-08 11:53:59     /go/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/zrpc/client.go:45 +0x65
2024-06-08 11:53:59 fim_server/fim_group/group_api/internal/svc.NewServiceContext({{{{0xc0006de245, 0x5}, {{...}, {...}, {...}, {...}, {...}, {...}, 0x0, 0x0, ...}, ...}, ...}, ...})
2024-06-08 11:53:59     /build/fim_group/group_api/internal/svc/servicecontext.go:38 +0x248
2024-06-08 11:53:59 main.main()
2024-06-08 11:53:59     /build/fim_group/group_api/group.go:28 +0x147
```
可能是etcd ip配置错误？
## 问题查找
浏览器搜索 empty etcd hosts 后，发现有人修改配置信息后正常运行
[github相关问题网址](https://github.com/zeromicro/go-zero/issues/2376)
检查group.go:28后，发现group_api使用了三个rpc服务，但yaml中只配置了两个
```yaml
Name: group
Host: 0.0.0.0
Port: 20024
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
Etcd: 10.0.0.22:2379
Redis:
  Addr: 10.0.0.21:6379
  Pwd:
  DB: 0
UserRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: userrpc.rpc
GroupRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: grouprpc.rpc
```
## 添加相关配置
```yaml
Name: group
Host: 0.0.0.0
Port: 20024
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
Etcd: 10.0.0.22:2379
Redis:
  Addr: 10.0.0.21:6379
  Pwd:
  DB: 0
UserRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: userrpc.rpc
FileRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: filerpc.rpc
GroupRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: grouprpc.rpc
```
## 重新部署group_api
deploy-group_api-1日志：
```shell
2024-06-08 16:09:48 连接mysql数据库成功
2024-06-08 16:09:48 2024-06-08 16:09:48  info   地址上送成功 group_api  10.0.0.8:20024  caller=etcd/delivery_address.go:29
2024-06-08 16:09:48 Starting server at 0.0.0.0:20024...
```
# kafka无法连接broker节点
## 问题发现
kafka日志信息：
无法连接到 node 1001 (/10.0.0.3:9092)
```shell
2024-06-08 16:15:46 java.io.IOException: Connection to 10.0.0.3:9092 (id: 1001 rack: null) failed.
2024-06-08 16:15:46     at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
2024-06-08 16:15:46     at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
2024-06-08 16:15:46     at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
2024-06-08 16:15:46     at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:131)
2024-06-08 16:15:46 [2024-06-08 08:15:46,056] INFO [Controller id=1001, targetBrokerId=1001] Client requested connection close from node 1001 (org.apache.kafka.clients.NetworkClient)
2024-06-08 16:15:46 [2024-06-08 08:15:46,156] INFO [Controller id=1001, targetBrokerId=1001] Node 1001 disconnected. (org.apache.kafka.clients.NetworkClient)
2024-06-08 16:15:46 [2024-06-08 08:15:46,156] WARN [Controller id=1001, targetBrokerId=1001] Connection to node 1001 (/10.0.0.3:9092) could not be established. Node may not be available. (org.apache.kafka.clients.NetworkClient)
2024-06-08 16:15:46 [2024-06-08 08:15:46,156] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker 10.0.0.3:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
```
todo
